### ISSUE TITLE
[BUG] Unable to login from windows

### ISSUE THREAD

**Issue by jwestrmaier** [unofficial-memsource/memsource-cli-client#22]
**Describe the bug**
Unable to login to memsource in Windows command line

**Affected version**

**To Reproduce**
C:\Windows\system32>memsource auth login --user-name "USERNAME" --password "PASSWORD" -c token -f value --debug
2019-12-30 13:09:29,172 DEBUG Starting new HTTP connection (1): "https:80
2019-12-30 13:09:29,179 DEBUG Incremented Retry for (url='//qa.memsource.com/web%22/api2/v1/auth/login'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
2019-12-30 13:09:29,180 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object
 at 0x0000007D2C6CB7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //qa.memsource.com/web%22/api2/v1/auth/login
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007D2C6CB7F0>: Failed
to establish a new connection: [Errno 11001] getaddrinfo failed')': //qa.memsource.com/web%22/api2/v1/auth/login
2019-12-30 13:09:29,183 DEBUG Starting new HTTP connection (2): "https:80
2019-12-30 13:09:29,184 DEBUG Incremented Retry for (url='//qa.memsource.com/web%22/api2/v1/auth/login'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
2019-12-30 13:09:29,185 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object
 at 0x0000007D2C6CBA90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //qa.memsource.com/web%22/api2/v1/auth/login
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007D2C6CBA90>: Failed
to establish a new connection: [Errno 11001] getaddrinfo failed')': //qa.memsource.com/web%22/api2/v1/auth/login
2019-12-30 13:09:29,188 DEBUG Starting new HTTP connection (3): "https:80
2019-12-30 13:09:29,190 DEBUG Incremented Retry for (url='//qa.memsource.com/web%22/api2/v1/auth/login'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
2019-12-30 13:09:29,191 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object
 at 0x0000007D2C6CBC10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': //qa.memsource.com/web%22/api2/v1/auth/login
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007D2C6CBC10>: Failed
to establish a new connection: [Errno 11001] getaddrinfo failed')': //qa.memsource.com/web%22/api2/v1/auth/login
2019-12-30 13:09:29,194 DEBUG Starting new HTTP connection (4): "https:80
HTTPConnectionPool(host='"https', port=80): Max retries exceeded with url: //qa.memsource.com/web%22/api2/v1/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00
00007D2CEF5310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 944, in send
    self.connect()
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000007D2CEF5310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\cliff\app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\cliff\display.py", line 116, in run
    column_names, data = self.take_action(parsed_args)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\auth\v1\login.py", line 30, in take_action
    response = api.login(body=vars(parsed_args))
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api\authentication_api.py", line 55, in login
    (data) = self.login_with_http_info(**kwargs)  # noqa: E501
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api\authentication_api.py", line 115, in login_with_http_info
    return self.api_client.call_api(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api_client.py", line 326, in call_api
    return self.__call_api(resource_path, method,
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api_client.py", line 158, in __call_api
    response_data = self.request(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api_client.py", line 368, in request
    return self.rest_client.POST(url,
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\rest.py", line 272, in POST
    return self.request("POST", url,
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\rest.py", line 162, in request
    r = self.pool_manager.request(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\request.py", line 79, in request
    return self.request_encode_body(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='"https', port=80): Max retries exceeded with url: //qa.memsource.com/web%22/api2/v1/auth/login (Caused by NewConnectionError('<urllib3.connec
tion.HTTPConnection object at 0x0000007D2CEF5310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Traceback (most recent call last):
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\http\client.py", line 944, in send
    self.connect()
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 184, in connect
    conn = self._new_conn()
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000007D2CEF5310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jiri.westrmaier\AppData\Local\Programs\Python\Python38\Scripts\memsource.exe\__main__.py", line 7, in <module>
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\memsource.py", line 105, in main
    return memsource.run(argv)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\cliff\app.py", line 279, in run
    result = self.run_subcommand(remainder)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\cliff\app.py", line 400, in run_subcommand
    result = cmd.run(parsed_args)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\cliff\display.py", line 116, in run
    column_names, data = self.take_action(parsed_args)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\auth\v1\login.py", line 30, in take_action
    response = api.login(body=vars(parsed_args))
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api\authentication_api.py", line 55, in login
    (data) = self.login_with_http_info(**kwargs)  # noqa: E501
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api\authentication_api.py", line 115, in login_with_http_info
    return self.api_client.call_api(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api_client.py", line 326, in call_api
    return self.__call_api(resource_path, method,
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api_client.py", line 158, in __call_api
    response_data = self.request(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\api_client.py", line 368, in request
    return self.rest_client.POST(url,
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\rest.py", line 272, in POST
    return self.request("POST", url,
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\memsource_cli\rest.py", line 162, in request
    r = self.pool_manager.request(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\request.py", line 79, in request
    return self.request_encode_body(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "c:\users\jiri.westrmaier\appdata\local\programs\python\python38\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='"https', port=80): Max retries exceeded with url: //qa.memsource.com/web%22/api2/v1/auth/login (Caused by NewConnectionError('<urllib3.connec
tion.HTTPConnection object at 0x0000007D2CEF5310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by zerodayz** [comment]
@jwestrmaier check your URLs are correct, error like "getaddrinfo failed" usually means the system can't resolve the address into IP address. From first look it looks like the URL is wrong.

**Comment by zerodayz** [comment]
Did you add to your memsourcerc file:

`export MEMSOURCE_URL="https://qa.memsource.com/web"`
Or how do you export the URL variable in Windows.

This was added in 6eb8e4b

**Comment by zerodayz** [comment]
You should be also able to use Command Line Option to use custom URL:

`  --ms-auth-url <auth-url>
                        Authentication URL (Env: MEMSOURCE_URL) `

**Comment by jwestrmaier** [comment]
Resolved. I have allready run memsource on Windows.
Question : could you please help me how to get "uid" from "memsource project create" command?

**Comment by jwestrmaier** [comment]
i have this command "memsource project create --name "JW%date%-%time::=-%" --target-langs cs --source-lang en" and I would need to get UID from this command and set this uid in next command (create job)

**Comment by zerodayz** [comment]
Add `-f value -c uid` to the end of your command

**Comment by zerodayz** [comment]
Closing as issue was resolved. If you still have any issues please re-open this issue.
