### ISSUE TITLE
[BUG] No module named 'memsource_cli.memsource - unable to run memsource now

### ISSUE THREAD

**Issue by ludekjanda** [unofficial-memsource/memsource-cli-client#5]
**Describe the bug**
I updated my resource with the Install from Git script. 

$ memsource --help
Traceback (most recent call last):
  File "/home/ljanda/git/memsource-cli-client/.memsource/bin/memsource", line 11, in <module>
    load_entry_point('memsource-cli', 'console_scripts', 'memsource')()
  File "/home/ljanda/git/memsource-cli-client/.memsource/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ljanda/git/memsource-cli-client/.memsource/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/ljanda/git/memsource-cli-client/.memsource/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/ljanda/git/memsource-cli-client/.memsource/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'memsource_cli.memsource'

**Affected version**
Latest 

**To Reproduce**
Update with the script Install from Git from README

```

$ memsource --help
Traceback (most recent call last):
  File "/home/ljanda/git/memsource-cli-client/.memsource/bin/memsource", line 11, in <module>
    load_entry_point('memsource-cli', 'console_scripts', 'memsource')()
  File "/home/ljanda/git/memsource-cli-client/.memsource/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ljanda/git/memsource-cli-client/.memsource/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/ljanda/git/memsource-cli-client/.memsource/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/ljanda/git/memsource-cli-client/.memsource/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'memsource_cli.memsource'

```

**Comment by zerodayz** [comment]
@ludekjanda  it must be caused by https://github.com/unofficial-memsource/memsource-cli-client/commit/f68624062b78724a89d6f49efce919a171fd5185  however checking the CI https://travis-ci.com/unofficial-memsource/memsource-cli-client/jobs/241422536 it builds fine.

Is it possible to remove .memsource completely and re-run the update script?

**Comment by zerodayz** [comment]
Edited the update script: https://github.com/unofficial-memsource/memsource-cli-client/blob/master/README.md#install-from-github

Here is the part that has been added:
```
else
  cd memsource-cli-client/
  rm -Rf .memsource
  if [[ -f $(which python3) ]];
  then
    python3 -m venv --system-site-packages .memsource
  else
    if [[ ! -f $(which virtualenv) ]];
    then
      sudo yum -y install python-virtualenv
    fi
    virtualenv --system-site-packages .memsource
    for py in $(find memsource_cli -name "*.py"); do sed -i -e 's#/usr/bin/env python3#/usr/bin/env python#' $py; done
  fi
  source .memsource/bin/activate
```

Basically even if .memsource exists with old client memsource_cli, it will remove it and install new one with memsource-cli.

Let me know how it went.

**Comment by zerodayz** [comment]
Resolved by recreating the directory from the scratch. Update has failed because of the package name change memsource_cli -> memsource-cli in https://github.com/unofficial-memsource/memsource-cli-client/commit/f68624062b78724a89d6f49efce919a171fd5185
